# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      PGDATABASE_URL: postgres://mkhululi97:gsPG4LUB95oEEliIQIzZu1pMDxWjjhxr@dpg-cj6g9macn0vc73a1k6h0-a.oregon-postgres.render.com/dbgreetingswebapp?ssl=true

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: create postgresql tables
        run: PGPASSWORD=pg123 psql -h localhost -U sampleuser -d greetings -a -f ./users.sql
      - name: run tests with postgresql
        run: npm test
        env:
          PGDATABASE_URL: postgres://mkhululi97:gsPG4LUB95oEEliIQIzZu1pMDxWjjhxr@dpg-cj6g9macn0vc73a1k6h0-a.oregon-postgres.render.com/dbgreetingswebapp?ssl=true
